### ISSUE TITLE
when train, G_loss is nan.

### ISSUE THREAD

**Issue by anth9137** [NetEase-GameAI/SPatchGAN#1]
When I train SPatchGAN using selfie2anime, G_loss is nan at First step.
My hw was RTX3090 x2 and runinning was below.
"python main.py --dataset selfie2anime --augment_type resize_crop --suffix 20210825 --phase train --img_size 64 --batch_size 1"
I attach my conda env(conda_list.txt) and all messages (problems.txt).

[conda_list.txt](https://github.com/NetEase-GameAI/SPatchGAN/files/7046154/conda_list.txt)
[problems.txt](https://github.com/NetEase-GameAI/SPatchGAN/files/7046185/problems.txt)

I want to know my mistake and howto fix it. Thank you.

**Comment by xunings** [comment]
Hi,
Can you try the default img_size (256)?
There are 6 downsampling layers in D by default, 2 in the initial feature extraction layer and 4 for the 4 scales. The feature maps will be downsampled from 64x64 to 1x1, making the standard deviation feature meaningless.

**Comment by anth9137** [comment]
Sorry to late reply. It works well! Thank you.
